### PR TITLE
recoil implementation

### PR DESCRIPTION
**Pull request by parweb**

### CODE REVIEW

**Comment by satansdeer** [comment]
Hi @parweb, could you please brief me on what this PR is about?

**Comment by JohannesKlauss** [comment]
@satansdeer Instead of the custom cube store, it uses facebooks recoil as a state management tool.

**Comment by satansdeer** [comment]
Looks cleaner tbh, merged it

**Comment by satansdeer** [comment]
@all-contributors please add @parweb and @satansdeer for maintenance

**Pull request merged**
